/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DAO_SLR } from "./DAO_SLR";
export type { DonationReceiptPrinter } from "./DonationReceiptPrinter";
export type { DonorManager } from "./DonorManager";
export type { OrganizationManager } from "./OrganizationManager";
export type { ProjectManager } from "./ProjectManager";
