/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DAO_SLR } from "./DAO_SLR";
export type { DonationReceipt } from "./DonationReceipt";
export type { Organization } from "./Organization";
export type { Project } from "./Project";
