/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AddProject__factory } from "./AddProject__factory";
export { Donate__factory } from "./Donate__factory";
export { Lock__factory } from "./Lock__factory";
export { SLRToken__factory } from "./SLRToken__factory";
export { Vote__factory } from "./Vote__factory";
