/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DAO_SLR__factory } from "./DAO_SLR__factory";
export { DonationReceipt__factory } from "./DonationReceipt__factory";
export { Organization__factory } from "./Organization__factory";
export { Project__factory } from "./Project__factory";
