/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DAO_SLR__factory } from "./DAO_SLR__factory";
export { DonationReceiptPrinter__factory } from "./DonationReceiptPrinter__factory";
export { DonorManager__factory } from "./DonorManager__factory";
export { OrganizationManager__factory } from "./OrganizationManager__factory";
export { ProjectManager__factory } from "./ProjectManager__factory";
