/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AddProject } from "./AddProject";
export type { Donate } from "./Donate";
export type { Lock } from "./Lock";
export type { SLRToken } from "./SLRToken";
export type { Vote } from "./Vote";
